### PR TITLE
Fix Image deprecation on RN >= 0.46 (#42)

### PR DESCRIPTION
**Pull request by radubatori**
Fixes the deprecation described in #42 and keeps compatibility with older RN versions.

### CODE REVIEW

**Comment by gvillenave** [comment]
Looks good! Can we get this merged?

**Comment by gvillenave** [comment]
Ping!

**Comment by cornedor** [comment]
I've published an update with these changes.

**Comment by radubatori** [comment]
Thanks 👍

**Comment by gvillenave** [comment]
Thanks!

**Pull request merged**
